repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --line-length=119

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E501,W503
          - --per-file-ignores=*/__init__.py:F401
          - --max-line-length=119
        additional_dependencies:
          - flake8-bugbear==22.7.1
          - flake8-builtins==1.5.3
          - pep8-naming==0.13.0
          - flake8-variables-names==0.0.5
          - flake8-commas==2.1.0
          - flake8-mock==0.3
          - flake8-printf-formatting==1.1.2
          - flake8-use-fstring==1.3
          - flake8-pytest-style==1.6.0
          - flake8-simplify==0.18.0
          - flake8-walrus==1.1.0
          - flake8-annotations==2.9.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args:
          - --unsafe
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.284
    hooks:
      - id: pyright

  - repo: https://github.com/hcodes/yaspeller.git
    rev: v8.0.1
    hooks:
      - id: yaspeller
