[tool.poetry]
name = "qmlcourse.ai"
version = "0.1.0"
description = ""
authors = ["SemyonSinchenko <semyonsinchenko@yahoo.com>"]
license = "CCBY-4.0"

[tool.poetry.dependencies]
python = "^3.7"
PennyLane = "^0.14.1"
numpy = "^1.20.1"
matplotlib = "^3.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
