title: QMLCourse
author: ODS Quantum Community
copyright: "2023"
logo: "logo.svg"

description: >-
  An adaptive and practical course about Quantum Machine Learning in the NISQ-era and related topics.

execute:
  execute_notebooks: cache
  run_in_temp: true
  timeout: -1

html:
  favicon: _static/index/qmlcourse_favicon.ico
  home_page_in_navbar: true
  use_repository_button: true
  use_issues_button: true
  use_binder_button: false
  binderhub_url: ""
  thebe: false
  baseurl: https://quantum-ods.github.io/qmlcourse/book/
  google_analytics_id: G-3B94SZ0WNF

notebook_interface: "notebook"

# repository:
#   url: https://github.com/quantum-ods/qmlcourse
#   path_to_book: "qmlcourse"

latex:
  latex_engine: "xelatex"
  latex_elements:
    preamble: >-
      \usepackage{amsmath}
      \usepackage{unicodemath}
      \usepackage{hyperref}
      \usepackage{physics}
      \usepackage{polyglossia}
      \setmainlanguage[babelshorthands = true]{russian}
      \setotherlanguage{english}
  use_jupyterbook_latex: true
  latex_documents:
    targetname: qmlcourse.tex

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    html_baseurl: https://quantum-ods.github.io/qmlcourse/
  extra_extensions:
    - sphinx_sitemap
    - sphinx_jupyterbook_latex

parse:
  myst_enable_extensions:
    - amsmath
    - physics

bibtex_bibfiles:
  - _bibliography/references.bib

repository:
  url: https://github.com/quantum-ods/qmlcourse
  path_to_book: qmlcourse
  branch: master
