name: deploy-book

# Only run this when the master branch changes
on:
  workflow_dispatch:
  pull_request:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@v2
      
      - name: Checkout branch with cache     
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: ./gh-pages

      - name: Copy cache for build book
        run: |
          cp -r ./gh-pages/_build/ ./qmlcourseRU/ || exit 0

      #Use cache
      - name: Copy cache dir for dependecies
        uses: actions/cache@v2
        env:
          cache-name: cache-poetry-modules
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-      

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install dependencies
        run: |
          poetry install
      # Build the book
      - name: Build the book
        run: |
          poetry run jupyter-book build ./qmlcourseRU
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourseRU
