name: deploy-book-cache

# Only run this when the master branch changes 
on:
  workflow_dispatch:
  pull_request:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.base_ref== 'master'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files

  deploy-book:
    runs-on: ubuntu-latest
    if: failure() != true
    needs: [pre-commit]
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@v2
      
      - name: Checkout branch with cache     
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: ./gh-pages

      - name: Copy cache for build book
        run: |
          cp -r ./gh-pages/_build/ ./qmlcourseRU/ || exit 0

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      #Use cache
      - name: Copy cache dir for dependecies
        uses: actions/cache@v2
        env:
          cache-name: cache-poetry-modules
        with:
          path: .venv
          key: venv2-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}          

      - name: Install dependencies
        run: |
          poetry install
      # Build the book
      - name: Build the book
        run: |
          poetry run jupyter-book build ./qmlcourseRU
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourseRU
