name: cd-stage

on:
  workflow_dispatch:
    inputs:
      build_pdf:
        description: 'build pdf book? (it is increase time workflow)'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

env:
  PUBLISH_BRANCH: web-page-stage

jobs:

  create-folder-for-latex:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:

      - name: checkout to build branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PUBLISH_BRANCH }}

      - run: |
          mkdir -p ./latex/

  build-and-deploy-book:
    needs: [create-folder-for-latex]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: qmlc-web-page-stage
      url: https://qmlc-web-page-stage.netlify.app

    steps:

      - name: checkout branch for build
        uses: actions/checkout@v3

      - name: install imagemagick
        run: |
          sudo apt install -y imagemagick

      - name: set up py3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          # cache: 'poetry'

      - name: set up conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge, psi4
          activate-conda: true

      - name: set up poetry
        uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true
          # installer-parallel: true

      - name: install dependencies
        run: |
          conda create python=3.8 -p .venv -y
          conda install psi4 -c psi4 -p .venv -y

          poetry install --no-interaction --no-root

      - name: build the book
        id: build_book
        env:
          DWAVE_TOKEN: ${{ secrets.DWAVE_TOKEN }}
        run: |
          poetry run jupyter-book toc migrate ./qmlcourse/_toc.yml -o ./qmlcourse/_toc.yml
          poetry run jupyter-book build ./qmlcourse

      - name: update publish dir to build branch
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourse/_build/html/
          publish_branch: ${{ env.PUBLISH_BRANCH }}

      - name: build latex files
        if: github.event.inputs.build_pdf == 'yes'
        env:
          DWAVE_TOKEN: ${{ secrets.DWAVE_TOKEN }}
        run: |
          sudo apt-get install texlive-latex-extra texlive-fonts-extra texlive-xetex latexmk
          poetry run jupyter-book build ./qmlcourse --builder latex

      - name: create pdf book
        if: github.event.inputs.build_pdf == 'yes'
        continue-on-error: true
        run: |
          cd ./qmlcourse/_build/latex/
          xelatex -interaction=nonstopmode qmlcourse.tex

      - name: send pdf book to build branch
        if: github.event.inputs.build_pdf == 'yes'
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourse/_build/latex/
          destination_dir: ./latex/
          publish_branch: ${{ env.PUBLISH_BRANCH }}
