name: deploy-book-master

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  create_folder_for_latex:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: checkout to building branch
        uses: actions/checkout@v3
        with:
          ref: web-page-master

      - run: |
          mkdir ./latex/

  deploy_book_master:
    needs: [create_folder_for_latex]
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout branch for build
        uses: actions/checkout@v3

      - name: install imagemagick
        run: |
          sudo apt install -y imagemagick

      - name: set up py3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: set up poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: load cached venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: build the book
        run: |
          export DWAVE_TOKEN="${{ secrets.DWAVE_TOKEN }}"
          poetry run jupyter-book toc migrate /home/runner/work/qmlcourse/qmlcourse/qmlcourse/_toc.yml -o /home/runner/work/qmlcourse/qmlcourse/qmlcourse/_toc.yml

          poetry run jupyter-book build ./qmlcourse

      - name: update publish dir to `web-page-master`
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourse/_build/html/
          publish_branch: web-page-master

      - name: build latex files
        run: |
          export DWAVE_TOKEN="${{ secrets.DWAVE_TOKEN }}"

          poetry run jupyter-book build ./qmlcourse --builder latex
